### ISSUE TITLE
Hammersmith Registry>Follow-up>Pregancy

### ISSUE THREAD

**Issue by afzalkhan500** [fhosking/cml-database#102]
For patient 1191 the pregnancy data doesn't match:

![image](https://github.com/user-attachments/assets/a865f45e-cac3-4a9e-be6d-1759a8e9ba68)
![image](https://github.com/user-attachments/assets/477d0fa1-c6f4-4740-9095-6e39becc4860)

**Comment by fhosking** [comment]
It seems that this is the raw data for pregnancy 1 record 1191

<img width="396" alt="image" src="https://github.com/user-attachments/assets/0f7c8d53-d1f1-4c4b-88a0-667905271bf0">

**Comment by fhosking** [comment]
I see, it looks like, months ago i figured out this issue, but did not upload a corrected dataset. I've uploaded a corrected dataset:

<img width="569" alt="image" src="https://github.com/user-attachments/assets/2e548fd8-0638-4f29-97b2-a471022f731e">

**Comment by afzalkhan500** [comment]
Everything looks good but "No of TKI Before Pregnancy" should be 0 and this is a manual entry field.

**Comment by fhosking** [comment]
Yes, i see the issue. Fixed:

<img width="560" alt="image" src="https://github.com/user-attachments/assets/092c4211-c3af-4aa2-94c5-b93a9bea19f8">

**Comment by afzalkhan500** [comment]
Great. Could you put the "Expected Date of Delivery" same place as in MS Access rather than bottom of the page.

**Comment by fhosking** [comment]
Reordered table

<img width="556" alt="image" src="https://github.com/user-attachments/assets/d4c0146b-0708-4377-a12e-4f499c584c6b">
