### ISSUE TITLE
Hammersmith Registry>Baseline>Disease Status at start...

### ISSUE THREAD

**Issue by afzalkhan500** [fhosking/cml-database#103]
Phase of disease should be:
1:Chronic Phase TKI
2:Accel Phase TKI
3:Blast Phase TKI

![image](https://github.com/user-attachments/assets/44625f8f-1a4d-4692-bfd6-308c9688ad13)
![image](https://github.com/user-attachments/assets/4d4a9690-aaef-4495-99cd-5ff7b0e7208b)

**Comment by fhosking** [comment]
Changed from

1, Chronic
2, Accelerated
3, Blast

to

1, Chronic Phase TKI
2, Accel Phase TKI
3, Blast Phase TKI
