### ISSUE TITLE
Hammersmith Registry>Treatment and toxicity

### ISSUE THREAD

**Issue by afzalkhan500** [fhosking/cml-database#104]
Below calulated fields are not working:

![image](https://github.com/user-attachments/assets/13e7679a-a333-4e11-b757-88b932037629)
![image](https://github.com/user-attachments/assets/5ea330bd-df97-4518-be72-231421abeede)

**Comment by fhosking** [comment]
How do you calculate it?

**Comment by afzalkhan500** [comment]
Time since first TKI line = Current Evaluation Date - very 1st Evaulation Date from record 1

So for patient 85 Treatment and Toxicity record 10:

Time since 1st TKI line = 08/02/2016-02/03/2015 and convert to months

**Comment by fhosking** [comment]
Added, please review

<img width="555" alt="image" src="https://github.com/user-attachments/assets/fc9cbaf7-37e2-4bff-bb37-7e1d6176fa96">
