### ISSUE TITLE
Hammersmith Registry>Baseline>Haematological Data>Add ELTS Score

### ISSUE THREAD

**Issue by afzalkhan500** [fhosking/cml-database#111]
Under "Risk Score" could you add following two fields in the same format as Sokal score:

1. ELTS Score
2. ELTS score manual:

**Comment by afzalkhan500** [comment]
The ELTS Score is calculated using:

0.0025 x (age/10)^3 + 0.0615 x spleen + 0.1052 x blasts + 0.4104 x (platelet count/1000)^-05

Age comes from Baseline>Clinical Data at Diagnosis>Age at diagnosis
Spleen comes from Baseline>Clinical Data at Diagnosis>Spleen Size (cm below the costal margin):
Blasts comes from Baseline>Haematological Data>% PB Blasts
Platelets come form Baseline>Haematological Data>Platelets

**Comment by fhosking** [comment]
Is the ELTS score the "Euroscore"? Assuming yes for now

**Comment by afzalkhan500** [comment]
Perfect!
