### ISSUE TITLE
Hammersmith Registry>Haematological Data>Sokal score

### ISSUE THREAD

**Issue by afzalkhan500** [fhosking/cml-database#112]
"Sokal Score" is calculated using following formula:

Exp 0.0116 x (age – 43.4) + 0.0345 x (spleen – 7.51) + 0.1880 x [(platelet count/700)^2-0.563] + 0.0887 x (blasts -2.10)

**Comment by afzalkhan500** [comment]
Age comes from Baseline>Clinical Data at Diagnosis>Age at diagnosis
Spleen comes from Baseline>Clinical Data at Diagnosis>Spleen Size (cm below the costal margin):
Blasts comes from Baseline>Haematological Data>% PB Blasts
Platelets come form Baseline>Haematological Data>Platelets

**Comment by fhosking** [comment]
I have implemented the sokal score but clearly it will require some testing:

<img width="540" alt="image" src="https://github.com/user-attachments/assets/ea5d18ed-c407-43ad-a272-1935ee9c0243">

I note that if not all the values are present, the score does not calculate

**Comment by afzalkhan500** [comment]
The score is not right. Is it possible to look at how the below website does the calculation?
https://clincasequest.hospital/sokal-index-cml/

**Comment by fhosking** [comment]
Updated Sokal score

https://redcap.imperial.ac.uk/redcap_v14.7.3/DataEntry/index.php?pid=91&id=1382&page=baseline&event_id=535&instance=1
<img width="552" alt="image" src="https://github.com/user-attachments/assets/53b3765c-573f-4dbc-adca-e7e932c030d6">

> @CALCTEXT(
>     if(
>         (
>             [dem_age_dia] <> "" AND
>             [cda_spleensize] <> "" AND
>             [hae_platelets] <> "" AND
>             [hae_blastsinperipheralblood] <> ""
>         ),
>         (
>             exponential(([dem_age_dia] - 43.4) * 0.0116) +
>             ([cda_spleensize] - 7.51) * 0.0345 +
>             ((([hae_platelets] / 700) * ([hae_platelets] / 700) - 0.563) * 0.1880) +
>             ([hae_blastsinperipheralblood] - 2.10) * 0.0887
>         ),
>         " "
>     )
> )
