### ISSUE TITLE
Baseline: Wrong transcript

### ISSUE THREAD

**Issue by fhosking** [fhosking/cml-database#17]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Fearg/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Fearg/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Frontend   label | Access Variable   Label | Access Variable   Name | REDCap variable   name
-- | -- | -- | --
Molecular Biology / BaselineData
BCR-ABL 1 Transcript   Type
Type of   transcript | Type of transcript | TypeOfTranscript | mol_typeoftranscript

</body>

</html>

---

REDCap is picking wrong transcript type (eg for patient 100 it should be e14a2 and REDCap is showing e13a2)

**Comment by fhosking** [comment]
<img width="623" alt="image" src="https://github.com/fhosking/cml-database/assets/69717469/0b362f23-7b15-496e-a750-976b27b33768">

This is worth investigating. It certainly seems that the Type of transcript value for record 100 is '3'. 

I can't find the encoding for these anywhere.

**Comment by afzalkhan500** [comment]
1, e1a2
2, e13a2
3, e14a2
4, Unknown Type
5, Other

**Comment by fhosking** [comment]
Updated

<img width="441" alt="image" src="https://github.com/fhosking/cml-database/assets/69717469/b1169689-5fe4-41e4-9e95-95d8f6dbb1a2">
