### ISSUE TITLE
?Social table missing

### ISSUE THREAD

**Issue by fhosking** [fhosking/cml-database#42]
<img width="180" alt="image" src="https://github.com/fhosking/cml-database/assets/69717469/6971873c-54a3-4d53-a460-c20b309da6b2">

Have these fields been imported to REDCap?

**Comment by fhosking** [comment]
<img width="547" alt="image" src="https://github.com/fhosking/cml-database/assets/69717469/fbe89276-73e2-43cd-940d-7ab4095e6c6a">

Added this missing section and imported data. 0 values have been imported as 'No' rather than blank, though I think this could alternatively be imported as blank.

**Comment by afzalkhan500** [comment]
checked
