### ISSUE TITLE
UK Registry / Baseline: BSA

### ISSUE THREAD

**Issue by fhosking** [fhosking/cml-database#43]
<img width="551" alt="image" src="https://github.com/fhosking/cml-database/assets/69717469/256211c6-1c0e-4dda-b465-58dba6691eac">

The UK registry has this field 'BSA' which I'm not familar with, and am unclear about whether this also exists in the Hammersmith registry.

**Comment by afzalkhan500** [comment]
Doesn't exist in Hammersmith registry

**Comment by afzalkhan500** [comment]
BSA=((height (cm) x weight (kg)/3600)1/2

**Comment by fhosking** [comment]
Added for UK registry
