### ISSUE TITLE
UK Registry / Demographic Data / Comorbidities mismatch

### ISSUE THREAD

**Issue by fhosking** [fhosking/cml-database#44]
It seems that in the comorbidities in the UK registry are:

<img width="264" alt="image" src="https://github.com/fhosking/cml-database/assets/69717469/53ed9f91-b535-4a0e-b000-6b977d6efb31">

Whereas in the Hammersmith registry they are:

<img width="491" alt="image" src="https://github.com/fhosking/cml-database/assets/69717469/0e817155-2fa5-4c1b-81e3-44302fb96c5f">

These don't seem to cleanly match. Please could I have confirmation about how these fields map to each other, and if any should be kept unique and separate.

The main issues I think are matching Genitourinary and Thyroid.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Fearg/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Fearg/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

UK   Registry | Hammersmith   Registry
-- | --
Neurological   Disorders | ~
Cardiovascular   Disorders | Cardiovascular
Hypertension | Hypertension
Diabetes | Diabetes
Genitourinary | ~
Chronic   Renal Disease | Renal
Psychiatric   Illness | Psychiatric
Thyroid | Other   Metabolic
Gastrointestinal | Gastrointestinal
Respiratory | Respiratory
Cancer | Malignancy
Neurological   Disorders Types | ~
Any   Other Comorbidities | Other   comorbidity
~ | Blood
~ | Liver
~ | Immunological
~ | Musculoskeletal
~ | Reproduction
~ | Skin
~ | ENT

</body>

</html>

**Comment by afzalkhan500** [comment]
Amalgamate the two lists, remove duplicate (Neurological Disorders Types) and include all headings across both.

**Comment by fhosking** [comment]
Added
