### ISSUE TITLE
UK Registry / Fields not in Hammersmith Registry

### ISSUE THREAD

**Issue by fhosking** [fhosking/cml-database#45]
Please confirm that these fields are collected in the UK registry but are not collected in the Hammersmith registry:

- District
- Local Hospital
- Informed Consent
- Informed Consent Date
- Employment status
- No of Cigs Smoked Daily

**Comment by afzalkhan500** [comment]
Add this information to Hammersmith registry also.

**Comment by fhosking** [comment]
Added all fields - note, district will be determined by the site the user is assigned to
