### ISSUE TITLE
UK Registry / Clinical Data / Symtoms Mismatch

### ISSUE THREAD

**Issue by fhosking** [fhosking/cml-database#46]
It seems that the symtoms listed in the UK registry clinical data section:

<img width="276" alt="image" src="https://github.com/fhosking/cml-database/assets/69717469/adc90e5a-f1f6-45db-b946-e52a517a8286">

Do not cleanly match the Hammersmith constitutional symtoms section:

<img width="246" alt="image" src="https://github.com/fhosking/cml-database/assets/69717469/39ea9f27-d6b2-4710-b0e9-ce2a293604aa">

Please could you confirm how these are to map to oneanother

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Fearg/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Fearg/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

UK   Registry | Hammersmith   Registry
-- | --
WeightLoss | Weight   loss
BonePain | Bone   pain
BleedingBruising | Bleeding-Easy   bruising
Infection | ~
Fever | Fever
AbdominalPain | Abdominal   pain
Fatigue | ~
Other   Disease Related Symptoms | Other   Disease Related Symptoms
~ | Night   sweats
~ | Splenomegaly
~ | Hepatomegaly

</body>

</html>

**Comment by afzalkhan500** [comment]
Add infection, fatigue to Hammersmith registry and amalgamate.

**Comment by fhosking** [comment]
Merged the two lists:

<img width="247" alt="image" src="https://github.com/fhosking/cml-database/assets/69717469/d32e8d18-d05e-4e25-9898-270e6823232e">
