### ISSUE TITLE
UK Registry / Chromosome Analysis / Matching to Hammersmith

### ISSUE THREAD

**Issue by fhosking** [fhosking/cml-database#47]
This page on the UK registry, in particular the lower half Chromosome banding (metaphase) analysis:

<img width="565" alt="image" src="https://github.com/fhosking/cml-database/assets/69717469/bba0fcd3-36b4-4eca-89d8-a854e428a217">

Seems to correspond to two seperate pages in the Hammersmith Registry, baseline cytogenetics:

<img width="538" alt="image" src="https://github.com/fhosking/cml-database/assets/69717469/7274ae29-f061-45a8-b21d-b8c3b0d78020">

As well as follow up data Chromosome banding (metaphase) analysis:

<img width="780" alt="image" src="https://github.com/fhosking/cml-database/assets/69717469/ab267114-d12b-469c-afc6-a967af69360f">

Please could you confirm how these relate to one another. Perhaps we should import the first analysis from the UK registry into the baseline page, and then subsequent analyses to the follow up pages?

**Comment by afzalkhan500** [comment]
Correct.
