### ISSUE TITLE
UK Registry / BaseLine / Neurological Disorders Types

### ISSUE THREAD

**Issue by fhosking** [fhosking/cml-database#50]
<img width="319" alt="image" src="https://github.com/fhosking/cml-database/assets/69717469/92f46d11-64d1-45ef-8846-702346b37dd4">

I don't believe there is any corresponding field in the Hammersmith registry as this field in the UK registry. Unless there is, I will add this field for the UK registry records only? 

Do you know what options there are on the dropdown?

**Comment by afzalkhan500** [comment]
In comorbidities for each one ticked we need a space to specify what type and not just for neurological.

**Comment by fhosking** [comment]
I think the issue when I wrote this was that there is no 'neurological disorders' option in the Hammersmith registry. However, they have now been amalgamated. I will ensure that each one generates a follow up notes field for the users to add details for the Hammersmith users. Would you like this feature to also exist for the rUK users? This does not seem to be present in the current UK registry.

**Comment by afzalkhan500** [comment]
Yes, that's great!

**Comment by fhosking** [comment]
Notes field established for rUK users when neurological disorder selected from comorbidities

<img width="500" alt="image" src="https://github.com/user-attachments/assets/92ca374e-47b6-4e06-8518-60dfe3e61055">

**Comment by fhosking** [comment]
This issue seems to be resolved but please feel free to reopen for any reason
