### ISSUE TITLE
 Registry / BaseLine / Number of cigs smoked daily

### ISSUE THREAD

**Issue by fhosking** [fhosking/cml-database#52]
<img width="281" alt="image" src="https://github.com/fhosking/cml-database/assets/69717469/ba6bd7eb-464e-4e32-8925-0af08f833830">

I don't believe there is any corresponding field in the Hammersmith registry as this field in the UK registry. Unless there is, I will add this field for the UK registry records only?

**Comment by afzalkhan500** [comment]
There is no in Hammersmith registry

**Comment by afzalkhan500** [comment]
Add to Hammersmith registry.

**Comment by fhosking** [comment]
Number of cigs smoked daily is now available for all records
