### ISSUE TITLE
UK Registry / BaseLine / JAK

### ISSUE THREAD

**Issue by fhosking** [fhosking/cml-database#53]
In the data export, there are these two variables:~

<img width="302" alt="image" src="https://github.com/fhosking/cml-database/assets/69717469/5dac1fb1-a780-4cca-8d08-34ef08d1daf9">

- sJAK2	
- sJAK2Percentage

It's unclear to me where these exist on the user interface. Perhaps they have since been disabled? Should we import these?

**Comment by afzalkhan500** [comment]
Please remove any JAK2 fields from UK registry.

**Comment by fhosking** [comment]
JAK2 has not been imported
