### ISSUE TITLE
UK Registry / BaseLine / Smoker coding

### ISSUE THREAD

**Issue by fhosking** [fhosking/cml-database#54]
In the hammersmith registry the data seems to be encoded into 1/0 (presumably, yes/no) whereas the UK registry is encoded "Non Smoker"/"Former Smoker"/"Current Smoker"/"Unknown"

I will merge the data into the Hammersmith registry format. However, please let me know if you'd prefer another approach

**Comment by afzalkhan500** [comment]
No. Please keep to the UK registry coding for both.

**Comment by fhosking** [comment]
Can I confirm that, in the UK registry, the options must be 'Any smoking history past or present' and 'No smoking history past or present' or something to that effect?

**Comment by afzalkhan500** [comment]
Yes correct as it is, but could you please add date of stopping for previous smoker.

**Comment by fhosking** [comment]
Added date of stopping

<img width="534" alt="image" src="https://github.com/user-attachments/assets/3707673d-4852-4007-a542-40e9042f5e75">

**Comment by fhosking** [comment]
This issue seems to be resolved but please feel free to reopen for any reason
