### ISSUE TITLE
UK Registry / BaseLine / Type of Transcript coding

### ISSUE THREAD

**Issue by fhosking** [fhosking/cml-database#55]
It seems that, in the UK registry, the encodings for 'Type of transcript' are:
"B3a2"
"B2a2"
"B2a2 and B3a2"
"Other"
"unknown"

However, the codings in the Hammersmith registry is:

1, e1a2
2, e13a2
3, e14a2
4, Unknown Type
5, Other

I'm not really sure how to match these up. For now,  these are not imported.

**Comment by afzalkhan500** [comment]
Dropdown should be e13a2, e14a2, e13a2+e14a2, unknown, other please specify. b3a2=e14a2, b2a2=e13a2.

**Comment by fhosking** [comment]
OK - I have imported data from the UK registry in the Hammersmith registry format
