### ISSUE TITLE
UK Registry / Molecular / Date of test

### ISSUE THREAD

**Issue by fhosking** [fhosking/cml-database#56]
<img width="547" alt="image" src="https://github.com/fhosking/cml-database/assets/69717469/85ec19f8-f718-432d-9113-a6726bb59191">

I think that in the UK registry, there is a separate date for BCRABL Transcript type/control Gene and BCRABL result.

<img width="701" alt="image" src="https://github.com/fhosking/cml-database/assets/69717469/e5c20dbe-9654-4cf1-b8f8-c64b5709af06">

I don't think this is the case in the Hammersmith Registry.

Looking at the data, the two separate dates in the UK regisry are 90% identical and 10% very similar. Presume we should merge these into one date to match the Hammersmith Registry? If so, presume prefering the Transcript type/control gene date.

**Comment by afzalkhan500** [comment]
Yes! correct.
