### ISSUE TITLE
TKI lines (Hammersmith Registry)

### ISSUE THREAD

**Issue by afzalkhan500** [fhosking/cml-database#58]
"Which TKI" in TKI Lines is currently a number-it should be drug name (Imatinib, dasatinib, etc)
![image](https://github.com/fhosking/cml-database/assets/169662104/953868f8-0ad1-4dd9-b5dd-c985d23aadc0)

**Comment by fhosking** [comment]
Updated to:

1, Imatinib
2, Dasatinib
3, Nilotinib
4, Bosutinib
5, Ponatinib
6, None
7, ABL001 (Asciminib)

**Comment by afzalkhan500** [comment]
Could you please change ABL001 and just have Asciminib.

**Comment by fhosking** [comment]
Removed 'ABL001 ()'

<img width="415" alt="image" src="https://github.com/user-attachments/assets/68d87a71-19a1-43de-9faf-3048bac3c400">
