### ISSUE TITLE
Annual FU system and toxicity type (Hammersmith Registry)

### ISSUE THREAD

**Issue by afzalkhan500** [fhosking/cml-database#59]
For each "System" there should only be certain toxicities showing in the "Toxicity type" pulldown menu. eg for System>Cardiovascular it should only be angina, chest pain, fluid retention, hypertension, myocardial infarction, other, PAH, palpitations, PAOD. At the moment is is showing all toxicities.

![image](https://github.com/fhosking/cml-database/assets/169662104/29a41b44-aa49-4632-9c17-5f1c85cea2a8)

**Comment by fhosking** [comment]
Is there a way to create a table showing all the combinations of system and toxicities?

**Comment by fhosking** [comment]
I think this will be tricky to impliment as REDCap doesn't have great real time filtering features for dropdown fields. We can filter dropdowns, but only when the page loads. Therefore, we will need to have the page save and reload when the system is selected, which will allow the page to filter the toxicity. This will take some time however - i've scheduled this in and will update in the future.

**Comment by fhosking** [comment]
I have added a filter for the System and Toxicity type. However, it only works when the page is refreshed. I may add a function to automatically refresh the page when this field is updated - which will ensure the filter works although at the cost of annoying the users. I note also that there is some tidying up to do on this section of the form.

**Comment by fhosking** [comment]
Great. I've set it up so the page auto refreshes when you select systemid, which then filters the toxicity type.

<img width="680" alt="image" src="https://github.com/user-attachments/assets/6783ab0a-2b86-4e18-a008-fdfff1fca338">
