### ISSUE TITLE
Hammersmith Registry/Baseline/Disease status at start/At 1st eval at HH

### ISSUE THREAD

**Issue by afzalkhan500** [fhosking/cml-database#62]
In Baseline>Disease status at start TKI/At 1st eval at HH the Response options should be:

ResponseDefinitionID | ResponseDefinition
1 | none
2 | PD
3 | CHR
4 | Ph+ ≤ 35%
5 | CCyR
6 | MMoR
7 | CMR4
8 | CMR4.5
9 | CMR5
11 | NE

**Comment by fhosking** [comment]
Is this definitely correct? At present, BaselineData DiseaseStatus contains only 0, 1 and 2 values:

<img width="215" alt="image" src="https://github.com/user-attachments/assets/1e1fdd78-7006-48c3-bd5a-50672dd81b4f">

**Comment by afzalkhan500** [comment]
I mean the response options:
![image](https://github.com/user-attachments/assets/8f916524-6e8e-4be3-9f9b-da343cbe134a)

**Comment by afzalkhan500** [comment]
These should be changed to:
ResponseDefinitionID | ResponseDefinition
1 | none
2 | PD
3 | CHR
4 | Ph+ ≤ 35%
5 | CCyR
6 | MMoR
7 | CMR4
8 | CMR4.5
9 | CMR5
11 | NE

**Comment by fhosking** [comment]
Recoded

<img width="545" alt="image" src="https://github.com/user-attachments/assets/fac26ee2-a77a-4aa2-8926-06cba2a6ba1c">
