### ISSUE TITLE
Hammersmith Registry Baseline> Disease status at start TKI/At 1st eval at HH the 1st TKI start date 

### ISSUE THREAD

**Issue by afzalkhan500** [fhosking/cml-database#63]
Baseline> Disease status at start TKI/At 1st eval at HH the 1st TKI start date should be taken from TKI Lines and it the start date of the first TKI lines.

**Comment by fhosking** [comment]
Please could you specify the variable for Disease Status Disease status at start of TKI/Disease status at 1st evaluation at HH and start date?
Is this from the access table tblPostTKIFailure?

At present, the variable being imported is BaselineData -> DiseaseStatus and DateOfDiagnosis

**Comment by afzalkhan500** [comment]
Sorry, ignore this.
