### ISSUE TITLE
Hammersmith Registry/Treatment and Toxicity

### ISSUE THREAD

**Issue by afzalkhan500** [fhosking/cml-database#64]
In Treatment and Toxicity there is something wrong with: 
![image](https://github.com/user-attachments/assets/9bcbab59-e36c-4c95-916e-32ccfbcd70a4)

**Comment by fhosking** [comment]
Should be fixed now:

<img width="450" alt="image" src="https://github.com/user-attachments/assets/565aa93f-5b80-40a6-a675-82a04ff3a19b">
