### ISSUE TITLE
Hammersmith Registry/Annual FU/median dose

### ISSUE THREAD

**Issue by afzalkhan500** [fhosking/cml-database#66]
In Annual Follow-Up Drug 1 should change “system median dose” to “median dose” and move it so it is below maximum daily dose.

**Comment by afzalkhan500** [comment]
Keep same order as below for all dosing:

![image](https://github.com/user-attachments/assets/9efdeab3-cad2-4753-8b43-e9b2ac3fa5b4)

**Comment by fhosking** [comment]
Reordered

<img width="450" alt="image" src="https://github.com/user-attachments/assets/870be5c0-730e-4c53-a4d3-943d951b5da6">

**Comment by afzalkhan500** [comment]
Average dose is still in wrong place. Should be following order:
![image](https://github.com/user-attachments/assets/9a0cbbc1-01ba-4a0d-a67c-254fdfb5fb53)

**Comment by fhosking** [comment]
Reordered

<img width="532" alt="image" src="https://github.com/user-attachments/assets/9d75b19b-2cd5-461f-aaf3-302c5be74163">
