### ISSUE TITLE
Hammersmith Registry/Post TKI Failure

### ISSUE THREAD

**Issue by afzalkhan500** [fhosking/cml-database#69]
Post TKI Failure in below should be Post TKI therapy:

![image](https://github.com/user-attachments/assets/32adce3d-d9c7-4972-907e-990a9f6b3adb)

**Comment by fhosking** [comment]
I can't see Post TKI therapy in the above? Post TKI Chemotherapy?

**Comment by afzalkhan500** [comment]
Ignore this
