### ISSUE TITLE
Hammersmith Registry/TKI lines/Disease status

### ISSUE THREAD

**Issue by afzalkhan500** [fhosking/cml-database#71]
In TKI Lines “Disease status at TKI change” is currently a number. It should:

1 | none
2 | PD
3 | CHR
4 | BCR-ABL ratio <1%
5 | CCyR
6 | MMoR
7 | CMR4
8 | CMR4.5
9 | CMR5
10 | NE
11 | BCR-ABL ratio <10%
12 | MiHR

**Comment by fhosking** [comment]
Updated

<img width="450" alt="image" src="https://github.com/user-attachments/assets/8b379375-d213-457d-8b47-6953f649e483">
