### ISSUE TITLE
Hammersmith Registry/Survival status

### ISSUE THREAD

**Issue by afzalkhan500** [fhosking/cml-database#73]
In Survival Status “Which TKI at last follow-up” should be:

1 | Imatinib
2 | Dasatinib
3 | Nilotinib
4 | Bosutinib
5 | Ponatinib
6 | None
7 | ABL001 (Asciminib)

**Comment by fhosking** [comment]
I note that, in the raw data import, there are values between 1-11:

<img width="263" alt="image" src="https://github.com/user-attachments/assets/b47ef11e-0e5b-43a2-8ac8-9c16e4169b5e">

<img width="425" alt="image" src="https://github.com/user-attachments/assets/42f0dab1-33f8-453d-8ba3-20184c7aa965">

I have reimported the data, keeping the coded values above 1-7, and excluding the values 8-11

**Comment by fhosking** [comment]
Ok, thanks for confirming. I've reworked this section

<img width="555" alt="image" src="https://github.com/user-attachments/assets/3a29751a-3eac-42df-8d3e-984b488cdcbd">
