### ISSUE TITLE
Hammermsith Registry/Age at diagnosis

### ISSUE THREAD

**Issue by afzalkhan500** [fhosking/cml-database#74]
Age below is missing which is date of diagnosis-DOB:

![image](https://github.com/user-attachments/assets/09874531-c5cb-4d46-a26c-45aa0edf0409)

**Comment by fhosking** [comment]
Added current age calculation

<img width="400" alt="image" src="https://github.com/user-attachments/assets/ecd966e4-3200-4dcf-b1d9-db35ce8df0da">

**Comment by afzalkhan500** [comment]
This isn't right for patient 161:
![image](https://github.com/user-attachments/assets/3893bcd0-8b0b-4031-bbfd-80fb131e5341)
![image](https://github.com/user-attachments/assets/9b89b4e7-605e-4f0c-b236-91822e5755cb)

So Age (which should really be called "Age at Diagnosis") = Date of Diagnosis - DOB

Current age = Current date or date of death if patient has died - DOB

**Comment by fhosking** [comment]
Updated current age. It's a bit tricky to get to work so hopefully this is satisfactory

<img width="500" alt="image" src="https://github.com/user-attachments/assets/c419b8ce-d678-4dac-b70a-299588371167">

**Comment by fhosking** [comment]
Added age at diagnosis

<img width="565" alt="image" src="https://github.com/user-attachments/assets/6ea9d855-f062-49d9-961f-88d371dcbcbe">
