### ISSUE TITLE
Hammersmith Registry/Saving and scrolling

### ISSUE THREAD

**Issue by afzalkhan500** [fhosking/cml-database#76]
When you click Save&Stay in REDCap it scrolls to top of page every time. Can we get it to go to stay where it was as it takes a while to scroll to bottom of a long page every time you save?

**Comment by fhosking** [comment]
Interesting idea! I've really had to hack in to REDCap, but this should now be working!

**Comment by afzalkhan500** [comment]
Brilliant!
