### ISSUE TITLE
Hammersmith Registry/Treatment history 2

### ISSUE THREAD

**Issue by afzalkhan500** [fhosking/cml-database#78]
I think the below is missing in REDCap:

![image](https://github.com/user-attachments/assets/7208995e-f703-4c30-840f-42835c782cff)

**Comment by fhosking** [comment]
Should hopefully be fully available here:

![image](https://github.com/user-attachments/assets/3a73d5c4-f414-4ae8-8eba-d2c7929e0b8c)

**Comment by afzalkhan500** [comment]
"Toxicity with which TKI" is currently a number, it should be a TKI name (see TKI list a sent in other comments).

**Comment by afzalkhan500** [comment]
And supportive therapy should be Yes, No, Unknown

**Comment by fhosking** [comment]
Changed Toxicity with which TKI to multiple choice and supportive therapy to yes/no

<img width="500" alt="image" src="https://github.com/user-attachments/assets/c592f218-1832-416b-804c-4e1f5904f2c1">
