### ISSUE TITLE
Hammersmith Registry/Follow-up data

### ISSUE THREAD

**Issue by afzalkhan500** [fhosking/cml-database#79]
In REDCap clicking Follow-up should take you straight into Chromosome Banding but it instead shows Survival Status entry fields:

![image](https://github.com/user-attachments/assets/5a03986a-30c7-49d4-8648-d28d50fe5e6d)

**Comment by fhosking** [comment]
Ok, this has been updated:

<img width="500" alt="image" src="https://github.com/user-attachments/assets/6803f746-62a4-41a7-8405-15a6fab0a168">

<img width="500" alt="image" src="https://github.com/user-attachments/assets/67f31fff-0670-484f-a5e5-ed97db23ecba">
