### ISSUE TITLE
Hammersmith Registry/Chromosome banding

### ISSUE THREAD

**Issue by afzalkhan500** [fhosking/cml-database#80]
Auto calculation for % Ph+ metaphases (N Ph+ metaphases/N evaluated metaphases):

![image](https://github.com/user-attachments/assets/c322153c-c6f5-4ce3-aa56-085eff10254a)

**Comment by fhosking** [comment]
Added calculating field:

<img width="595" alt="image" src="https://github.com/user-attachments/assets/997f6936-5427-4bfa-945a-995ba817b185">

**Comment by afzalkhan500** [comment]
You can make all calculated percentages whole numbers

**Comment by fhosking** [comment]
Now rounds to nearest whole number

<img width="500" alt="image" src="https://github.com/user-attachments/assets/ed88ae84-68a2-4271-afd6-0cf07108b06d">
