### ISSUE TITLE
Hammersmith Registry/FISH

### ISSUE THREAD

**Issue by afzalkhan500** [fhosking/cml-database#81]
N scored nuclei Unknown and N positive nuclei Unknown should be dropdown with Yes and No.

![image](https://github.com/user-attachments/assets/62983a13-3f39-410f-b0ed-210cc039d758)

**Comment by afzalkhan500** [comment]
Auto calculation for % Positive Nuclei (N Positive Nuclei/N. Scored Nuclei)

**Comment by fhosking** [comment]
Reworked form and data import

<img width="580" alt="image" src="https://github.com/user-attachments/assets/e72d0b3e-c498-4c5b-a016-d8a12b92be7e">
