### ISSUE TITLE
Hammersmith Registry/Annual Follow-up/Treatment current status

### ISSUE THREAD

**Issue by afzalkhan500** [fhosking/cml-database#83]
Put Treatment status in same order as below:

![image](https://github.com/user-attachments/assets/702b0c0b-1841-4682-8675-95afaf46f4e8)

**Comment by afzalkhan500** [comment]
![image](https://github.com/user-attachments/assets/b6efc195-ba4d-472b-958a-4058ddbfe53b)

**Comment by fhosking** [comment]
Moved treatment current status to the end of the drug section

<img width="425" alt="image" src="https://github.com/user-attachments/assets/6e1a42b4-ce3f-4200-ad83-e7aac1620aea">
