### ISSUE TITLE
Hammersmith Registry/Annual FU/Toxicity/Other and other

### ISSUE THREAD

**Issue by afzalkhan500** [fhosking/cml-database#84]
When System is Other then the only dropdown option for Toxicity Type is Other:

![image](https://github.com/user-attachments/assets/c48060f1-697f-4b1c-a321-c6d095d0fca9)

![image](https://github.com/user-attachments/assets/a00e400c-a60b-4bf5-b4dd-3614357d16ca)

**Comment by afzalkhan500** [comment]
At the moment in REDCap there are many options under Toxicity type.

**Comment by fhosking** [comment]
Ok - when system is 'Other' there is no need to select a toxicity type. REDCap isn't very good at filtering dropdowns in real time, so if we need custom functionality we will have to write something ourselves

<img width="517" alt="image" src="https://github.com/user-attachments/assets/87d8143f-b007-48c6-b006-202ed4595f51">

**Comment by afzalkhan500** [comment]
Duplicate of #59 issue.
