### ISSUE TITLE
Hammersmith Registry/Annual FU/Toxicity/Toxicity Start Date

### ISSUE THREAD

**Issue by afzalkhan500** [fhosking/cml-database#85]
In REDCap Toxicity start Date is not a date field:

![image](https://github.com/user-attachments/assets/c4f7882d-8b7a-476f-baf7-d3aec27771ee)

**Comment by fhosking** [comment]
Toxicity start date now a date field

<img width="563" alt="image" src="https://github.com/user-attachments/assets/02dc73c5-aa8f-40d4-826c-cbfffa4428c1">
