### ISSUE TITLE
Which TKI post-AlloSCT TKI Coding

### ISSUE THREAD

**Issue by fhosking** [fhosking/cml-database#87]
Looks like Which TKI post-AlloSCT still isn't working. For patient 23 here is the MSAccess and REDCap screenshots:
![image](https://github.com/user-attachments/assets/260f95cf-0f54-48a2-9681-54a817006845)
![image](https://github.com/user-attachments/assets/cf98440c-677a-4b8d-866f-3148e9b07a26)

You can see that in Access Dasatinib is Line 2 but in REDCAP is Line 1.

Just be aware that "Which TKI post-AlloSCT" is different from "Which TKI post-AlloBMT". So clicking yes to "TKI post-AlloSCT" gives you the option to pick only one TKI in "Which TKI post-AlloSCT." "Which TKI post-AlloBMT" gives you the option for several TKI along with option for "Which line of TKI post-AlloBMT." Hope this makes sense otherwise we can set up a teams meeting as it is probably the only major item stopping us from moving to REDCap.

![image](https://github.com/user-attachments/assets/c039673e-448b-4fc5-add0-2f21eada551a)

**Comment by fhosking** [comment]
It seems like the issue is related to the encodings of the whichtkipostallobmt in the tblTKIsFailure Access object. We can see that record 23 has 3 and then 2 recorded as the values which at present correspond to our TKI codes, the first 5 of which are:

1, None
2, Imatinib
3, Dasatinib
4, Nilotinib
5, Bosutinib

<img width="536" alt="image" src="https://github.com/user-attachments/assets/db2eba67-1f95-46bd-87b9-bd6f055c76fa">

**Comment by fhosking** [comment]
I've found this lookup table which seems to correspond with your reference:

<img width="211" alt="image" src="https://github.com/user-attachments/assets/f99288c7-7245-46d1-a169-cf384ab578e9">

**Comment by fhosking** [comment]
However I can see this lookup table in access which seems to correspond to your reference:

<img width="234" alt="image" src="https://github.com/user-attachments/assets/46ddf64a-1031-4f35-b060-4aff42061618">

I've switched the encoding to this table for whichtkipostallobmt

**Comment by afzalkhan500** [comment]
Brilliant! That works for two patients I checked so yes go ahead and and do the same for Auto and DLI.

**Comment by afzalkhan500** [comment]
Yes, for same for chemo.

**Comment by fhosking** [comment]
Updated chemo whichtkiid and whichtkipostct

<img width="600" alt="image" src="https://github.com/user-attachments/assets/3b9616f0-5db5-433a-be68-5d2457f5734e">
