### ISSUE TITLE
Hammersmith Registry>Baseline>Biochemistry pre-TKI

### ISSUE THREAD

**Issue by afzalkhan500** [fhosking/cml-database#91]
There is a sentence from the top of the page which is missing which says "Enter biochemistry results not older than two weeks before 1st TKI start date: 15/12/2003." The date comes from Baseline>Disease status at start TKI/At 1st evel at HH>1st TKI start date:"

![image](https://github.com/user-attachments/assets/b684e2c3-028e-4692-9b11-5882a18a9f64)
![image](https://github.com/user-attachments/assets/26c15ef4-f6d4-4cab-a3bf-e224035a2ce2)

**Comment by fhosking** [comment]
Added warning:

<img width="579" alt="image" src="https://github.com/user-attachments/assets/65e01ba1-0908-433d-9f65-d5a345655055">

**Comment by afzalkhan500** [comment]
Brilliant. That works.
