### ISSUE TITLE
Hammersmith Registry>Follow-up>Chromosome Banding>% Ph + metaphases

### ISSUE THREAD

**Issue by afzalkhan500** [fhosking/cml-database#92]
If both "N evaluated metaphases" and "N Ph + metaphases" exist then it should automatically calculate "% Ph + metaphases" but if one or both are missing it should allow manual input of the percentage. This is required as some hospitals will just give a percentage without the metaphases data.

**Comment by fhosking** [comment]
Ok. In REDCap, it's slightly infeasible to have a field be calculated and also manually entered. What I've done is provided an automatic calculation next to the free text field:

<img width="544" alt="image" src="https://github.com/user-attachments/assets/50b4d942-62e0-4a70-aa89-5544ef97fba1">

**Comment by afzalkhan500** [comment]
When I try to manually enter value and save it come up with:
![image](https://github.com/user-attachments/assets/911ee994-a833-4fc6-8d98-3aa5d978b273)

**Comment by fhosking** [comment]
The first item on that list makes sense and i've corrected it

The second one doesn't really make sense so hopefully it's just a phantom issue which will go away now that the first is fixed

**Comment by afzalkhan500** [comment]
Both errors have gone.
