### ISSUE TITLE
Hammersmith Registry>Baseline

### ISSUE THREAD

**Issue by afzalkhan500** [fhosking/cml-database#93]
For the Follow-up tab you added jump-to tabs which make things easier than scrolling. Please do the same for Baseline:

![image](https://github.com/user-attachments/assets/726c71a8-9d0f-4d8c-9ddb-8c0407bae940)

![image](https://github.com/user-attachments/assets/7c61d692-9d30-4d7b-aedc-0056922750c1)

**Comment by afzalkhan500** [comment]
And the same for Response

**Comment by fhosking** [comment]
Added to baseline

<img width="595" alt="image" src="https://github.com/user-attachments/assets/4e78bbb3-b44d-4aca-987b-c207253c0751">

**Comment by fhosking** [comment]
Added to response

<img width="666" alt="image" src="https://github.com/user-attachments/assets/88169cd6-a08c-48e2-8630-617ade08bdc2">
