### ISSUE TITLE
Hammersmith Registry>Follow-up>Progression

### ISSUE THREAD

**Issue by afzalkhan500** [fhosking/cml-database#95]
It looks like REDCap is choosing Lympoid when it should be blank:

![image](https://github.com/user-attachments/assets/e137569b-9fca-4985-82d5-7154e24f49fa)
![image](https://github.com/user-attachments/assets/e40c3bab-590d-4da8-9564-6e3e613f17cc)

For patient 1360 it looks like when BC type exists it is choosing the right one but in above example when blank it reverts to Lymphoid:

![image](https://github.com/user-attachments/assets/7d65d5a7-6866-4947-87ab-72ca420c042d)
![image](https://github.com/user-attachments/assets/b269e9b9-f7a6-4d3f-8f73-509286addf66)

**Comment by fhosking** [comment]
Fixed incorrect incoding of blank BC type

<img width="262" alt="image" src="https://github.com/user-attachments/assets/18e4ee33-c97e-4cef-8570-d7c64ff1a425">

**Comment by afzalkhan500** [comment]
That works but I notice for patient 254 when only the date is entered and nothing else it picks Yes for "progr to AP/BC" when is should be No and picks Blastic phase when it should be blank.

![image](https://github.com/user-attachments/assets/673c79ef-a9b9-48e0-a749-b43afcef2cd5)
![image](https://github.com/user-attachments/assets/6b72de1c-a9cf-4381-97f4-30decf56cfd0)

**Comment by fhosking** [comment]
This is a side issue, maybe i should make it a separate issue, but there's something funny that I can see happening with record 254:

When I search the raw data from access for records with progression date #3 above 15-08-2006, it can't find record 254:

<img width="503" alt="image" src="https://github.com/user-attachments/assets/ffc4c9aa-72c1-472d-9d6d-106edc59b7f0">

When I search the raw data for episodes for record 254, it only finds 3 (all minus #3 above)

<img width="503" alt="image" src="https://github.com/user-attachments/assets/67acd4e4-69b5-484a-8d2a-9f7f7428e50d">

**Comment by afzalkhan500** [comment]
The reason you can only see three records is probably because the MS Access database has been updated since I sent you a copy a year ago, hence 4 rows, but the important thing is for record 15/01/2008 there should be no blast phase chosen. Hope this makes sense.

**Comment by fhosking** [comment]
It does seem that that is the way the data is being represented in the raw dataset:

<img width="669" alt="image" src="https://github.com/user-attachments/assets/f4e1cdfb-636f-45be-9f6c-b8f423a1b1dd">

I can't really seem to identify a mark in the data that could help me identify when a record should or shouldn't be blastic phase

<img width="680" alt="image" src="https://github.com/user-attachments/assets/856c7741-250e-4f27-ac56-31741ef3ce87">

**Comment by fhosking** [comment]
We could try again with a fresher dataset if you like?

**Comment by afzalkhan500** [comment]
Leave it for now I think it is probably due to my MS Access database being modified hence the discrepancies.
