### ISSUE TITLE
Hammersmith Registry>Baseline>Disease status...

### ISSUE THREAD

**Issue by afzalkhan500** [fhosking/cml-database#98]
% missing:

![image](https://github.com/user-attachments/assets/f7b52201-c311-49c9-8e4d-7458ed6e6e92)
![image](https://github.com/user-attachments/assets/da1d88af-b33e-4b40-a2f1-57258501029f)

**Comment by fhosking** [comment]
Added percent symbols

<img width="548" alt="image" src="https://github.com/user-attachments/assets/ada2264d-7a96-4a2e-b9be-dc17df0b7b1f">
