### ISSUE TITLE
Hammersmith Registry>Baseline>Immunophenotype on PB

### ISSUE THREAD

**Issue by afzalkhan500** [fhosking/cml-database#99]
Values need x100 and % sign needs adding:

![image](https://github.com/user-attachments/assets/fcdcf9c0-cefd-4ad7-b09d-79cacbc7d97f)

**Comment by fhosking** [comment]
Added % and muliplied by 100

<img width="647" alt="image" src="https://github.com/user-attachments/assets/8d58acad-7a6e-4106-932e-47fee6797a00">
